### ISSUE TITLE
tag a formal release

### ISSUE THREAD

**Issue by jonboulle** [go-inf/inf#2]
(shamelessly channelling @onlyjob from https://github.com/coreos/go-tspi/issues/6#issue-143649549)

Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning

**Comment by speter** [comment]
Thanks for the feedback; very reasonable request. Tagged v0.9.0.

**Comment by onlyjob** [comment]
Thank you. :)
