### ISSUE TITLE
can u provide float64 convert to decimal function

### ISSUE THREAD

**Issue by rfyiamcool** [go-inf/inf#7]
see title, I think it's useful, thank u.

**Comment by speter** [comment]
Thanks for the feedback, but I don't intend to provide float conversion (this is also stated in the package docs). Using floats to handle decimal numbers is, in general, inherently flawed, so it is not encouraged and/or supported by this package. (If you're absolutely certain that this is what you need to do, one way to achieve it is to go through a string representation.)

**Comment by hjizettle** [comment]
There is a practical problem here when you have existing code that works with both floats and decimals and you have to bridge them. Should I go through the string representation in that case?

**Comment by hjizettle** [comment]
Aha that's what you said, I was a bit fast. ;)
